name: CI
on: [push]
jobs:
  buildWebGL:
    runs-on: ubuntu-latest
    container: gableroux/unity3d:2019.2.3f1-webgl
    steps:
        - name: Checkout Project
          uses: actions/checkout@v1

        - name: Decrypt the license file
          run: openssl aes-256-cbc -d -in .github/Unity_v2019.x.ulf.enc -k ${{ secrets.UNITY_LICENSE_DECRYPT_KEY }} >> .github/Unity_v2019.x.ulf

        - name: Activate Unity
          run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -manualLicenseFile .github/Unity_v2019.x.ulf || exit 0

        - name: Build WebGL Player
          run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -projectPath . -executeMethod BuildAndDeployGame.BuildScript.BuildWebGl

        - name: Publish WebGL Build
          uses: actions/upload-artifact@v1
          with:
            name: unity_ci_test_webgl
            path: ./Build-WebGl/

  buildWindows:
    runs-on: ubuntu-latest
    container: gableroux/unity3d:2019.2.3f1-windows
    steps:
        - name: Checkout Project
          uses: actions/checkout@v1

        - name: Decrypt the license file
          run: openssl aes-256-cbc -d -in .github/Unity_v2019.x.ulf.enc -k ${{ secrets.UNITY_LICENSE_DECRYPT_KEY }} >> .github/Unity_v2019.x.ulf

        - name: Activate Unity
          run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -manualLicenseFile .github/Unity_v2019.x.ulf || exit 0

        - name: Build Windows Player
          run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -projectPath . -buildWindows64Player ./bin-win64/unity_ci_test.exe

        - name: Publish Windows Build
          uses: actions/upload-artifact@v1
          with:
            name: unity_ci_test_win64
            path: ./bin-win64
